(require 'ert)
(require 'json)
(require 'subr-x)

(add-to-list 'load-path
             (expand-file-name "../../emacs" (file-name-directory load-file-name)))

(require 'hyprmacs-ipc)
(require 'hyprmacs-session)
(require 'hyprmacs-buffers)
(require 'hyprmacs)

(defun hyprmacs-test--decode (frame)
  "Decode FRAME and return message alist."  
  (json-parse-string (string-trim-right frame)
                     :object-type 'alist
                     :array-type 'list
                     :null-object nil
                     :false-object :json-false))

(ert-deftest hyprmacs-ipc-encodes-manage-workspace-envelope ()
  (let* ((message (hyprmacs-ipc-make-envelope
                   "manage-workspace"
                   "1"
                   '((adopt_existing_clients . t))
                   "2026-04-15T12:00:00Z"))
         (encoded (hyprmacs-ipc-encode-message message))
         (decoded (hyprmacs-test--decode encoded)))
    (should (equal (alist-get 'version decoded) 1))
    (should (equal (alist-get 'type decoded nil nil #'equal) "manage-workspace"))
    (should (equal (alist-get 'workspace_id decoded nil nil #'equal) "1"))
    (should (equal (alist-get 'timestamp decoded nil nil #'equal)
                   "2026-04-15T12:00:00Z"))
    (should (equal
             (alist-get 'adopt_existing_clients
                        (alist-get 'payload decoded)
                        nil nil #'equal)
             t))))

(ert-deftest hyprmacs-ipc-decodes-state-dump-shape ()
  (let* ((fixture "{\"version\":1,\"type\":\"state-dump\",\"workspace_id\":\"1\",\"timestamp\":\"2026-04-15T12:00:00Z\",\"payload\":{\"managed\":true,\"controller_connected\":true,\"eligible_clients\":[{\"client_id\":\"0xabc123\",\"title\":\"foot\",\"app_id\":\"foot\",\"floating\":false}],\"managed_clients\":[],\"selected_client\":null,\"input_mode\":null}}\n")
         (decoded (hyprmacs-ipc-decode-message fixture))
         (payload (alist-get 'payload decoded)))
    (should (equal (alist-get 'type decoded nil nil #'equal) "state-dump"))
    (should (equal (alist-get 'managed payload nil nil #'equal) t))
    (should (equal (alist-get 'controller_connected payload nil nil #'equal) t))
    (should (equal (length (alist-get 'eligible_clients payload nil nil #'equal)) 1))
    (should (equal (alist-get 'managed_clients payload nil nil #'equal) '()))
    (should-not (alist-get 'selected_client payload nil nil #'equal))
    (should-not (alist-get 'input_mode payload nil nil #'equal))))

(ert-deftest hyprmacs-ipc-mode-roundtrip ()
  (should (equal (hyprmacs-ipc-mode-to-wire 'emacs-control) "emacs-control"))
  (should (equal (hyprmacs-ipc-mode-to-wire 'client-control) "client-control"))
  (should-not (hyprmacs-ipc-mode-to-wire 'other-mode))
  (should (eq (hyprmacs-ipc-mode-from-wire "emacs-control") 'emacs-control))
  (should (eq (hyprmacs-ipc-mode-from-wire "client-control") 'client-control))
  (should-not (hyprmacs-ipc-mode-from-wire "other-mode")))

(ert-deftest hyprmacs-session-fake-transport-captures-and-applies-fixtures ()
  (hyprmacs-session-reset)
  (hyprmacs-buffer-reset)
  (hyprmacs-session-use-fake-transport)
  (hyprmacs-session-request-state "1")
  (let* ((outbox (hyprmacs-session-fake-outbox))
         (request (hyprmacs-test--decode (car outbox))))
    (should (equal (length outbox) 1))
    (should (equal (alist-get 'type request nil nil #'equal) "request-state"))
    (should (equal (alist-get 'workspace_id request nil nil #'equal) "1")))

  (hyprmacs-session-fake-receive
   "{\"version\":1,\"type\":\"workspace-managed\",\"workspace_id\":\"1\",\"timestamp\":\"2026-04-15T12:00:00Z\",\"payload\":{\"managed\":true,\"controller_connected\":true}}\n")
  (should (eq (plist-get hyprmacs-session-state :managed) t))
  (should (eq (plist-get hyprmacs-session-state :controller-connected) t))

  (hyprmacs-session-fake-receive
   "{\"version\":1,\"type\":\"state-dump\",\"workspace_id\":\"1\",\"timestamp\":\"2026-04-15T12:00:00Z\",\"payload\":{\"managed\":true,\"controller_connected\":true,\"eligible_clients\":[{\"client_id\":\"0xabc123\",\"title\":\"foot\",\"app_id\":\"foot\",\"floating\":false}],\"managed_clients\":[\"0xabc123\"],\"selected_client\":\"0xabc123\",\"input_mode\":\"emacs-control\"}}\n")
  (should (equal (plist-get hyprmacs-session-state :workspace-id) "1"))
  (should (equal (plist-get hyprmacs-session-state :last-message-type) "state-dump"))
  (should (equal (plist-get hyprmacs-session-state :managed-clients) '("0xabc123")))
  (should (equal (length (plist-get hyprmacs-session-state :associated-buffers)) 1))
  (should (buffer-live-p (hyprmacs-buffer-for-client "0xabc123")))
  (should (equal (plist-get hyprmacs-session-state :selected-client) "0xabc123"))
  (should (eq (plist-get hyprmacs-session-state :input-mode) 'emacs-control))
  (hyprmacs-buffer-reset))

(ert-deftest hyprmacs-session-state-dump-syncs-managed-buffer-lifecycle ()
  (hyprmacs-session-reset)
  (hyprmacs-buffer-reset)

  (hyprmacs-session-fake-receive
   "{\"version\":1,\"type\":\"state-dump\",\"workspace_id\":\"1\",\"timestamp\":\"2026-04-15T12:00:00Z\",\"payload\":{\"managed\":true,\"controller_connected\":true,\"eligible_clients\":[{\"client_id\":\"0xaaa\",\"title\":\"foot-a\",\"app_id\":\"foot\",\"floating\":false},{\"client_id\":\"0xbbb\",\"title\":\"foot-b\",\"app_id\":\"foot\",\"floating\":false}],\"managed_clients\":[\"0xaaa\",\"0xbbb\"],\"selected_client\":\"0xaaa\",\"input_mode\":\"emacs-control\"}}\n")
  (should (buffer-live-p (hyprmacs-buffer-for-client "0xaaa")))
  (should (buffer-live-p (hyprmacs-buffer-for-client "0xbbb")))

  (hyprmacs-session-fake-receive
   "{\"version\":1,\"type\":\"state-dump\",\"workspace_id\":\"1\",\"timestamp\":\"2026-04-15T12:00:01Z\",\"payload\":{\"managed\":true,\"controller_connected\":true,\"eligible_clients\":[{\"client_id\":\"0xaaa\",\"title\":\"foot-a\",\"app_id\":\"foot\",\"floating\":false}],\"managed_clients\":[\"0xaaa\"],\"selected_client\":\"0xaaa\",\"input_mode\":\"emacs-control\"}}\n")
  (should (buffer-live-p (hyprmacs-buffer-for-client "0xaaa")))
  (should-not (hyprmacs-buffer-for-client "0xbbb"))
  (hyprmacs-buffer-reset))

(ert-deftest hyprmacs-session-sends-selection-and-mode-commands ()
  (hyprmacs-session-reset)
  (hyprmacs-session-use-fake-transport)
  (hyprmacs-session-set-selected-client "1" "0xabc")
  (hyprmacs-session-set-input-mode "1" 'client-control)
  (hyprmacs-session-set-layout
   "1"
   '((selected_client . "0xabc")
     (input_mode . "client-control")
     (visible_clients . ("0xabc"))
     (hidden_clients . ())
     (rectangles . (((client_id . "0xabc") (x . 0) (y . 0) (width . 100) (height . 100))))
     (stacking_order . ("0xabc"))))
  (let* ((frames (hyprmacs-session-fake-outbox))
         (first (hyprmacs-test--decode (nth 0 frames)))
         (second (hyprmacs-test--decode (nth 1 frames)))
         (third (hyprmacs-test--decode (nth 2 frames))))
    (should (equal (alist-get 'type first nil nil #'equal) "set-selected-client"))
    (should (equal (alist-get 'client_id (alist-get 'payload first) nil nil #'equal) "0xabc"))
    (should (equal (alist-get 'type second nil nil #'equal) "set-input-mode"))
    (should (equal (alist-get 'mode (alist-get 'payload second) nil nil #'equal) "client-control"))
    (should (equal (alist-get 'type third nil nil #'equal) "set-layout"))
    (should (equal (alist-get 'visible_clients (alist-get 'payload third) nil nil #'equal) '("0xabc")))))

(ert-deftest hyprmacs-session-sends-float-managed-client ()
  (hyprmacs-session-reset)
  (hyprmacs-session-use-fake-transport)
  (hyprmacs-session-float-managed-client "1" "0xabc")
  (let* ((frame (hyprmacs-test--decode (car (hyprmacs-session-fake-outbox))))
         (payload (alist-get 'payload frame)))
    (should (equal (alist-get 'type frame nil nil #'equal) "float-managed-client"))
    (should (equal (alist-get 'workspace_id frame nil nil #'equal) "1"))
    (should (equal (alist-get 'client_id payload nil nil #'equal) "0xabc"))))

(ert-deftest hyprmacs-session-sends-summon-candidate-requests ()
  (hyprmacs-session-reset)
  (hyprmacs-session-use-fake-transport)
  (hyprmacs-session-list-summon-candidates "1")
  (hyprmacs-session-summon-client "1" "0xabc")
  (let* ((frames (hyprmacs-session-fake-outbox))
         (first (hyprmacs-test--decode (nth 0 frames)))
         (second (hyprmacs-test--decode (nth 1 frames))))
    (should (equal (alist-get 'type first nil nil #'equal) "list-summon-candidates"))
    (should (equal (alist-get 'type second nil nil #'equal) "summon-client"))
    (should (equal (alist-get 'client_id (alist-get 'payload second) nil nil #'equal) "0xabc"))))

(ert-deftest hyprmacs-summon-client-uses-completing-read-choice ()
  (hyprmacs-session-reset)
  (hyprmacs-session-use-fake-transport)
  (cl-letf (((symbol-function 'hyprmacs--wait-seconds)
             (lambda (&rest _)
               (hyprmacs-session-fake-receive
                "{\"version\":1,\"type\":\"summon-candidates\",\"workspace_id\":\"1\",\"timestamp\":\"2026-04-24T00:00:00Z\",\"payload\":{\"candidates\":[{\"client_id\":\"0xabc\",\"workspace_id\":\"2\",\"app_id\":\"foot\",\"title\":\"remote shell\"}]}}\n")))
            ((symbol-function 'completing-read)
             (lambda (_prompt choices &rest _)
               (caar choices))))
    (hyprmacs-summon-client "1"))
  (let* ((frames (hyprmacs-session-fake-outbox))
         (first (hyprmacs-test--decode (nth 0 frames)))
         (second (hyprmacs-test--decode (nth 1 frames))))
    (should (equal (alist-get 'type first nil nil #'equal) "list-summon-candidates"))
    (should (equal (alist-get 'type second nil nil #'equal) "summon-client"))
    (should (equal (alist-get 'client_id (alist-get 'payload second) nil nil #'equal) "0xabc"))))

(ert-deftest hyprmacs-session-tracks-summon-candidate-workspace ()
  (hyprmacs-session-reset)
  (hyprmacs-session-fake-receive
   "{\"version\":1,\"type\":\"summon-candidates\",\"workspace_id\":\"7\",\"timestamp\":\"2026-04-24T00:00:00Z\",\"payload\":{\"candidates\":[{\"client_id\":\"0xabc\",\"workspace_id\":\"2\",\"app_id\":\"foot\",\"title\":\"remote\"}]}}\n")
  (should (equal (plist-get hyprmacs-session-state :summon-candidates-workspace-id) "7"))
  (should (equal (alist-get 'client_id
                            (car (plist-get hyprmacs-session-state :summon-candidates))
                            nil nil #'equal)
                 "0xabc")))

(ert-deftest hyprmacs-summon-client-does-not-reuse-stale-candidates-for-other-workspace ()
  (hyprmacs-session-reset)
  (hyprmacs-session-use-fake-transport)
  (setq hyprmacs-session-state
        (plist-put hyprmacs-session-state :summon-candidates-workspace-id "9"))
  (setq hyprmacs-session-state
        (plist-put hyprmacs-session-state :summon-candidates
                   '(((client_id . "0xstale") (workspace_id . "8") (app_id . "foot") (title . "stale")))))
  (cl-letf (((symbol-function 'hyprmacs--wait-seconds)
             (lambda (&rest _)
               (hyprmacs-session-fake-receive
                "{\"version\":1,\"type\":\"summon-candidates\",\"workspace_id\":\"1\",\"timestamp\":\"2026-04-24T00:00:00Z\",\"payload\":{\"candidates\":[{\"client_id\":\"0xfresh\",\"workspace_id\":\"2\",\"app_id\":\"foot\",\"title\":\"fresh\"}]}}\n")))
            ((symbol-function 'completing-read)
             (lambda (_prompt choices &rest _)
               (caar choices))))
    (hyprmacs-summon-client "1"))
  (let* ((frames (hyprmacs-session-fake-outbox))
         (first (hyprmacs-test--decode (nth 0 frames)))
         (second (hyprmacs-test--decode (nth 1 frames))))
    (should (equal (alist-get 'type first nil nil #'equal) "list-summon-candidates"))
    (should (equal (alist-get 'workspace_id first nil nil #'equal) "1"))
    (should (equal (alist-get 'type second nil nil #'equal) "summon-client"))
    (should (equal (alist-get 'client_id (alist-get 'payload second) nil nil #'equal) "0xfresh"))))

(ert-deftest hyprmacs-command-set-input-mode-defaults-to-client-control ()
  (hyprmacs-session-reset)
  (hyprmacs-session-use-fake-transport)
  (hyprmacs-set-input-mode "7")
  (let* ((frame (hyprmacs-test--decode (car (hyprmacs-session-fake-outbox)))))
    (should (equal (alist-get 'type frame nil nil #'equal) "set-input-mode"))
    (should (equal (alist-get 'workspace_id frame nil nil #'equal) "7"))
    (should (equal (alist-get 'mode (alist-get 'payload frame) nil nil #'equal) "client-control"))))

(ert-deftest hyprmacs-set-input-mode-selects-client-for-current-managed-buffer ()
  (hyprmacs-session-reset)
  (hyprmacs-buffer-reset)
  (hyprmacs-session-use-fake-transport)
  (let ((buffer-a (hyprmacs-buffer-ensure-for-client "0xaaa" "foot"))
        (buffer-b (hyprmacs-buffer-ensure-for-client "0xbbb" "foot")))
    (unwind-protect
        (progn
          (setq hyprmacs-session-state
                (plist-put hyprmacs-session-state :managed-clients '("0xaaa" "0xbbb")))
          (setq hyprmacs-session-state
                (plist-put hyprmacs-session-state :selected-client "0xaaa"))
          (switch-to-buffer buffer-b)
          (hyprmacs-set-input-mode "1")
          (let* ((frames (hyprmacs-session-fake-outbox))
                 (first (hyprmacs-test--decode (nth 0 frames)))
                 (second (hyprmacs-test--decode (nth 1 frames))))
            (should (equal (length frames) 2))
            (should (equal (alist-get 'type first nil nil #'equal) "set-selected-client"))
            (should (equal (alist-get 'client_id (alist-get 'payload first) nil nil #'equal) "0xbbb"))
            (should (equal (alist-get 'type second nil nil #'equal) "set-input-mode"))
            (should (equal (alist-get 'mode (alist-get 'payload second) nil nil #'equal) "client-control"))))
      (when (buffer-live-p buffer-a)
        (kill-buffer buffer-a))
      (when (buffer-live-p buffer-b)
        (kill-buffer buffer-b))
      (hyprmacs-buffer-reset))))

(ert-deftest hyprmacs-command-set-emacs-control-mode-sends-emacs-control ()
  (hyprmacs-session-reset)
  (hyprmacs-session-use-fake-transport)
  (hyprmacs-set-emacs-control-mode "7")
  (let* ((frame (hyprmacs-test--decode (car (hyprmacs-session-fake-outbox)))))
    (should (equal (alist-get 'type frame nil nil #'equal) "set-input-mode"))
    (should (equal (alist-get 'workspace_id frame nil nil #'equal) "7"))
    (should (equal (alist-get 'mode (alist-get 'payload frame) nil nil #'equal) "emacs-control"))))

(ert-deftest hyprmacs-manage-workspace-seeds-current-windows ()
  (hyprmacs-session-reset)
  (hyprmacs-session-use-fake-transport)
  (setq hyprmacs-session-state
        (plist-put hyprmacs-session-state :connection-status 'connected))
  (cl-letf (((symbol-function 'shell-command-to-string)
             (lambda (_cmd)
               "[{\"address\":\"0xaaa\",\"class\":\"foot\",\"title\":\"one\",\"floating\":0,\"workspace\":{\"id\":1}},{\"address\":\"0xbbb\",\"class\":\"foot\",\"title\":\"two\",\"floating\":1,\"workspace\":{\"id\":2}}]")))
    (hyprmacs-manage-current-workspace "1"))
  (let* ((frames (hyprmacs-session-fake-outbox))
         (types (mapcar (lambda (frame)
                          (alist-get 'type (hyprmacs-test--decode frame) nil nil #'equal))
                        frames))
         (seed-payload (alist-get 'payload (hyprmacs-test--decode (nth 1 frames)))))
    (should (equal types '("manage-workspace" "seed-client" "request-state")))
    (should (eq (alist-get 'floating seed-payload) :json-false))))

(ert-deftest hyprmacs-manage-workspace-auto-connects-when-disconnected ()
  (hyprmacs-session-reset)
  (hyprmacs-session-use-fake-transport)
  (let ((connect-calls 0))
    (cl-letf (((symbol-function 'hyprmacs-connect)
               (lambda (&optional _socket-path)
                 (setq connect-calls (1+ connect-calls))
                 (setq hyprmacs-session-state
                       (plist-put hyprmacs-session-state :connection-status 'connected))))
              ((symbol-function 'shell-command-to-string)
               (lambda (_cmd) "[]")))
      (hyprmacs-manage-current-workspace "1"))
    (let* ((frames (hyprmacs-session-fake-outbox))
           (types (mapcar (lambda (frame)
                            (alist-get 'type (hyprmacs-test--decode frame) nil nil #'equal))
                          frames)))
      (should (= connect-calls 1))
      (should (equal types '("manage-workspace" "request-state"))))))

(ert-deftest hyprmacs-default-workspace-prefers-active-hyprland-workspace ()
  (hyprmacs-session-reset)
  (cl-letf (((symbol-function 'shell-command-to-string)
             (lambda (_cmd) "{\"id\":2,\"name\":\"2\"}")))
    (should (equal (hyprmacs--default-workspace-id) "2"))))

(ert-deftest hyprmacs-default-workspace-prefers-active-over-session-state ()
  (hyprmacs-session-reset)
  (setq hyprmacs-session-state
        (plist-put hyprmacs-session-state :workspace-id "5"))
  (cl-letf (((symbol-function 'shell-command-to-string)
             (lambda (_cmd) "{\"id\":2,\"name\":\"2\"}")))
    (should (equal (hyprmacs--default-workspace-id) "2"))))

(ert-deftest hyprmacs-json-bool-normalization ()
  (should-not (hyprmacs--json-bool :json-false))
  (should-not (hyprmacs--json-bool :false))
  (should-not (hyprmacs--json-bool nil))
  (should-not (hyprmacs--json-bool 0))
  (should (hyprmacs--json-bool 1))
  (should (hyprmacs--json-bool t)))

(ert-deftest hyprmacs-layout-sync-hooks-cover-window-state-and-size-changes ()
  (let ((window-configuration-change-hook nil)
        (window-size-change-functions nil)
        (window-state-change-functions nil)
        (window-buffer-change-functions nil)
        (hyprmacs-layout-sync-enabled nil)
        (hyprmacs--layout-sync-timer nil))
    (hyprmacs-enable-layout-sync)
    (should (memq #'hyprmacs--schedule-auto-sync-layout window-configuration-change-hook))
    (should (memq #'hyprmacs--auto-sync-layout-size-change window-size-change-functions))
    (should (memq #'hyprmacs--auto-sync-layout-state-change window-state-change-functions))
    (should (memq #'hyprmacs--auto-sync-layout-buffer-change window-buffer-change-functions))
    (hyprmacs-disable-layout-sync)
    (should-not (memq #'hyprmacs--schedule-auto-sync-layout window-configuration-change-hook))
    (should-not (memq #'hyprmacs--auto-sync-layout-size-change window-size-change-functions))
    (should-not (memq #'hyprmacs--auto-sync-layout-state-change window-state-change-functions))
    (should-not (memq #'hyprmacs--auto-sync-layout-buffer-change window-buffer-change-functions))))

(ert-deftest hyprmacs-layout-sync-size-change-hook-schedules-sync ()
  (let ((hyprmacs-layout-sync-enabled t)
        (hyprmacs-session-state '(:connection-status connected :managed t :workspace-id "1"))
        (hyprmacs--layout-sync-in-flight nil)
        (hyprmacs--layout-sync-timer nil))
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (&rest _args) 'fake-layout-timer)))
      (hyprmacs--auto-sync-layout-size-change)
      (should (eq hyprmacs--layout-sync-timer 'fake-layout-timer)))))
